### ISSUE TITLE
[bug] error if test file import other typescript

### ISSUE THREAD

**Issue by HerringtonDarkholme** [power-assert-js/espower-typescript#16] opened 2016-04-19 09:06 UTC
I think this is a problem related to [typescirpt-simple](https://github.com/teppeis/typescript-simple/issues/37#issuecomment-211808094).

Reproduction:
package.json

``` json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha test.ts --compilers ts:espower-typescript/guess"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "espower-typescript": "^5.0.1",
    "mocha": "^2.4.5"
  }
}
```

dep.ts

``` typescript
export function test() {
  console.log('from ts')
}
```

test.ts

``` typescript
import {test} from './dep'

test()
```

Error stack

```
TypeError: Cannot read property 'text' of undefined
    at TypeScriptSimple.toJavaScript (/node_modules/typescript-simple/index.js:162:28)
    at TypeScriptSimple.compile (/node_modules/typescript-simple/index.js:71:25)
    at Object.loadTypeScript (/node_modules/espower-typescript/index.js:19:22)
    …略
```

Works fine with espower-typescript 4.1.0.

**Comment by muraken720** [comment] 2016-04-23 01:26
I have encounter the same issue.

**Comment by muraken720** [comment] 2016-04-28 00:24
I closed my issue.
In my case, the cause is "noEmitOnError: true".

I changed my tsconfig.json

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": true,
        "inlineSources": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noEmitOnError": false,    // true ---> false
        "preserveConstEnums": true,
        "removeComments": true,
        "declaration": true
    },
    "exclude": [
        "node_modules",
        "typings/browser",
        "typings/browser.d.ts"
    ]
}
```

**Comment by minodisk** [comment] 2016-08-23 06:52
In my case, this bug is fixed with updating `typescript-simple` package to 5.0.2. 
In default, `espower-typescript` uses 5.0.0: [package.json](https://github.com/power-assert-js/espower-typescript/blob/3a47d7255a803a15b0a0dae8f26e485e61d23439/package.json#L34)

**Comment by teppeis** [comment] 2016-10-24 15:15
@HerringtonDarkholme @muraken720 @minodisk 
This would be fixed by https://github.com/teppeis/typescript-simple/pull/47 fixes in Mac and Linux, but still remains in Windows.

**Comment by teppeis** [comment] 2017-02-23 09:27
Fixed in https://github.com/teppeis/typescript-simple/pull/66

**Closed by teppeis** 2017-02-23 09:27 UTC
